import pyautogui 
import pyautogui as escolha_opcao

opcao = pyautogui.confirm('Clique no botão desejado', buttons = ['Excel', 'Word', 'Notepad'])

if opcao == 'Excel':
    escolha_opcao.hotkey('win', 'r')
    escolha_opcao.sleep(2)
    escolha_opcao.typewrite('excel')
    escolha_opcao.press('enter')
    escolha_opcao.sleep(3)
    escolha_opcao.click(x=313, y=252)
    escolha_opcao.sleep(2)
    escolha_opcao.typewrite('Abrimos o excel')
    escolha_opcao.sleep(2)
    fecharJanela = escolha_opcao.getActiveWindow()
    fecharJanela.close()
    escolha_opcao.press('tab')
    escolha_opcao.press('tab')
    escolha_opcao.press('tab')
    escolha_opcao.press('tab')
    escolha_opcao.press('tab')
    escolha_opcao.sleep(2)
    escolha_opcao.press('enter')
elif opcao == 'Word':
    escolha_opcao.press('win')
    escolha_opcao.sleep(2)
    escolha_opcao.typewrite('Word')
    escolha_opcao.press('enter')
    escolha_opcao.sleep(2)
    escolha_opcao.click(x=-1107, y=368)
    escolha_opcao.sleep(2)
    escolha_opcao.typewrite('Abrimos o word')
    escolha_opcao.sleep(2)
    fecharJanela = escolha_opcao.getActiveWindow()
    fecharJanela.close()
    escolha_opcao.press('tab')
    escolha_opcao.press('tab')
    escolha_opcao.press('tab')
    escolha_opcao.press('tab')
    escolha_opcao.press('tab')
    escolha_opcao.sleep(2)
    escolha_opcao.press('enter')
elif opcao == 'Notepad':
    escolha_opcao.hotkey('win', 'r')
    escolha_opcao.sleep(2)
    escolha_opcao.typewrite('notepad')
    escolha_opcao.press('enter')
    escolha_opcao.sleep(3)
    escolha_opcao.typewrite('Abrimos o notepad')
    escolha_opcao.sleep(2)
    fecharJanela = escolha_opcao.getActiveWindow()
    fecharJanela.close()
